#!/bin/bash -ex
backup_drive=/Volumes/Backup
if [[ ! -e ${backup_drive} ]] ; then
    echo "Cannot find backup drive ${backup_drive}"
    exit 1
fi

mntpath=/tmp/mnt.$$
mkdir ${mntpath}
user=${LOGNAME}

# Reads server/volumes from ~/.backup_config.  Format:
# server mount_type vol1 vol2 ...
#
# Password for server stored in ~/.secrets/server

while read -r server server_type volumes ; do
    echo "Running for ${server}"
    pw=$(cat ~/.secrets/${server})

    #for vol in music home photo video vol1 ; do
    for vol in ${volumes} ; do
        # unmount drive if it's already mounted by me
        for m in $( mount | grep ${user}@${server} | grep ${vol} | perl -fane 'print "$F[2]\n"' ) ; do
            umount $m
        done

        # mount drive
        mount -t afp afp://${user}:${pw}@${server}/${vol} ${mntpath}

        # backup
        rsync -rav \
            --exclude '#recycle' \
            ${mntpath}/* \
            ${backup_drive}/${vol}

        # unmount drive
        umount ${mntpath}
    done
done < <( cat ~/.backup_config | grep -v '#' )

rmdir ${mntpath}
