#!/bin/bash
# 
# Finds all .pyc files with missing .py files and prompts to remove them
#

declare -a bad
for f in $( find . -name "*.pyc" )
do
    if [[ ! -f ${f/%.pyc/.py} ]] ; then
        bad[${#bad[@]}]=$f
    fi
done
if [[ -n "$bad" ]] ; then
	echo "Should remove files:"
	for f in ${bad[@]} ; do
		echo $f
	done
	echo 
	read -e -p "Remove them now? (Yes/No/Interactive) " yesno
	shopt -s nocasematch
	if [[ $yesno =~ ^(y(es)*)|(i(nteractive)*)$ ]] ; then
		interative=""
		if [[ $yesno =~ ^i(nteractive)*$ ]] ; then
			interactive=" -i "
		fi
		for f in ${bad[@]} ; do
			rm $interactive $f
		done
	fi
fi
